apiVersion: v1
kind: Secret
metadata:
  name: allegro-integrator-secrets
  namespace: oip
type: Opaque
stringData:
  DATABASE_ENCRYPTION_KEY: "REPLACE_VIA_CI_CD"
  KAFKA_SASL_USERNAME: "REPLACE_VIA_CI_CD"
  KAFKA_SASL_PASSWORD: "REPLACE_VIA_CI_CD"
  ALLEGRO_CLIENT_ID: "REPLACE_VIA_CI_CD"
  ALLEGRO_CLIENT_SECRET: "REPLACE_VIA_CI_CD"
