version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/platform"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "pip"
    directory: "/shared/python"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/platform/dashboard"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/platform"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "ci"
