#!/usr/bin/env bash
set -euo pipefail

echo "=== Open Integration Platform by Pinquark.com - Setup ==="
echo ""

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo "Found existing .env file, skipping generation."
else
    echo "Generating .env file with secure random keys..."

    ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null || openssl rand -base64 48)
    DB_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))" 2>/dev/null || openssl rand -base64 24)

    cat > "$ENV_FILE" << EOF
# Open Integration Platform by Pinquark.com - Configuration
# Generated by setup.sh

# Database
DB_PASSWORD=${DB_PASSWORD}

# Encryption key for credential vault (DO NOT LOSE - credentials become unreadable)
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# JWT secret for API authentication
JWT_SECRET_KEY=${JWT_SECRET}
EOF

    echo "Created .env with generated secrets."
    echo ""
    echo "IMPORTANT: Back up your ENCRYPTION_KEY. If lost, all stored credentials"
    echo "           become unrecoverable."
fi

echo ""
echo "Starting services..."
docker compose -f docker-compose.prod.yml up -d

echo ""
echo "Waiting for platform to become healthy..."
for i in $(seq 1 60); do
    if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
        echo "Platform is healthy!"
        break
    fi
    if [ "$i" -eq 60 ]; then
        echo "WARNING: Platform did not become healthy within 60 seconds."
        echo "Check logs: docker compose -f docker-compose.prod.yml logs platform"
        exit 1
    fi
    sleep 1
done

echo ""
echo "=== Setup Complete ==="
echo ""
echo "  Platform API:  http://localhost:8080"
echo "  Dashboard:     http://localhost:3000"
echo "  API Docs:      http://localhost:8080/docs"
echo ""
echo "Next steps:"
echo "  1. Create a tenant:  curl -X POST http://localhost:8080/api/v1/tenants -H 'Content-Type: application/json' -d '{\"name\": \"My Company\", \"slug\": \"my-company\"}'"
echo "  2. Create an API key: curl -X POST http://localhost:8080/api/v1/tenants/{tenant_id}/api-keys -H 'Content-Type: application/json' -d '{\"name\": \"dev\"}'"
echo "  3. Open the dashboard: http://localhost:3000"
echo ""
