from pinquark_common.schemas.common import (
    ErrorDetail,
    ErrorResponse,
    HealthCheck,
    HealthResponse,
    PaginatedResponse,
    SyncResult,
    SyncStatus,
)
from pinquark_common.schemas.ecommerce import (
    Address as EcommerceAddress,
    Buyer,
    Order,
    OrderLine,
    OrdersPage,
    OrderStatus,
    PriceUpdate,
    Product,
    StockItem,
)
from pinquark_common.schemas.courier import (
    CreateShipmentCommand,
    Parcel,
    PaymentDetails as CourierPaymentDetails,
    PickupPoint,
    ShipmentAddress,
    ShipmentParty,
    ShipmentResponse,
    ShipmentStatus,
    ShipmentStatusUpdate,
    Tracking,
)
from pinquark_common.schemas.wms import (
    Address as WmsAddress,
    Article,
    ArticleBatch,
    ArticleImage,
    Attribute,
    AttributeType,
    Contact,
    Contractor,
    DeleteArticleCommand,
    DeleteContractorCommand,
    DeleteDocumentCommand,
    DeletePositionCommand,
    Document,
    DocumentsWrapper,
    ErrorLog,
    Feedback,
    FeedbackAction,
    FeedbackEntity,
    Position,
    PositionArticle,
    PositionWrapper,
    Provider,
    UnitOfMeasure,
)

__all__ = [
    # --- Common ---
    "ErrorDetail",
    "ErrorResponse",
    "HealthCheck",
    "HealthResponse",
    "PaginatedResponse",
    "SyncResult",
    "SyncStatus",
    # --- E-commerce ---
    "Buyer",
    "EcommerceAddress",
    "Order",
    "OrderLine",
    "OrdersPage",
    "OrderStatus",
    "PriceUpdate",
    "Product",
    "StockItem",
    # --- Courier ---
    "CourierPaymentDetails",
    "CreateShipmentCommand",
    "Parcel",
    "PickupPoint",
    "ShipmentAddress",
    "ShipmentParty",
    "ShipmentResponse",
    "ShipmentStatus",
    "ShipmentStatusUpdate",
    "Tracking",
    # --- WMS (Pinquark REST API) ---
    "Article",
    "ArticleBatch",
    "ArticleImage",
    "Attribute",
    "AttributeType",
    "Contact",
    "Contractor",
    "DeleteArticleCommand",
    "DeleteContractorCommand",
    "DeleteDocumentCommand",
    "DeletePositionCommand",
    "Document",
    "DocumentsWrapper",
    "ErrorLog",
    "Feedback",
    "FeedbackAction",
    "FeedbackEntity",
    "Position",
    "PositionArticle",
    "PositionWrapper",
    "Provider",
    "UnitOfMeasure",
    "WmsAddress",
]
