services:
  courier-fxcouriers:
    build: .
    ports:
      - "8019:8000"
    env_file:
      - .env
    networks:
      - courier-net
    restart: unless-stopped

networks:
  courier-net:
    driver: bridge
