version: "3.8"

services:
  pinquark-wms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8000"
    env_file:
      - .env
    environment:
      WMS_APP_ENV: development
      WMS_LOG_LEVEL: DEBUG
    restart: unless-stopped

networks:
  default:
    name: pinquark-wms-dev
