apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: integrator-data
  namespace: pinquark-uat
  labels:
    app.kubernetes.io/part-of: pinquark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 1Gi
