apiVersion: v1
kind: Secret
metadata:
  name: integrator-secrets
  namespace: oip
  labels:
    app.kubernetes.io/part-of: pinquark
type: Opaque
stringData:
  DATABASE_ENCRYPTION_KEY: "REPLACE_VIA_CI_CD"
  KAFKA_SASL_USERNAME: "REPLACE_VIA_CI_CD"
  KAFKA_SASL_PASSWORD: "REPLACE_VIA_CI_CD"
