apiVersion: v1
kind: Service
metadata:
  name: integrator
  namespace: pinquark-uat
  labels:
    app.kubernetes.io/part-of: pinquark
    app.kubernetes.io/component: integrator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: integrator
