apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinquark-integrator
  namespace: oip
  labels:
    app.kubernetes.io/part-of: pinquark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: integrator-role
  namespace: oip
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: integrator-role-binding
  namespace: oip
subjects:
  - kind: ServiceAccount
    name: pinquark-integrator
    namespace: oip
roleRef:
  kind: Role
  name: integrator-role
  apiGroup: rbac.authorization.k8s.io
