apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pinquark-uat

resources:
  - ../../base

namePrefix: inpost-

commonLabels:
  app.kubernetes.io/name: inpost-integrator
  app.kubernetes.io/version: "3.0.0"
  category: courier
  system: inpost

patches:
  - target:
      kind: Deployment
      name: integrator
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.pinquark.com/integrations/courier/inpost:3.0.0-uat

generatorOptions:
  disableNameSuffixHash: true
